stages:
  - test
  - build-and-push
  - tag-image

test:
  stage: test
  image: node:latest
  script:
    - npm ci
    - npm run test:ci
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

build-and-push:
  stage: build-and-push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'

tag-image:
  stage: tag-image
  image:
    name: alpine:3.17.1
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache skopeo
    - skopeo login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - skopeo copy docker://${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} docker://${CONTAINER_IMAGE}:latest
    - skopeo copy docker://${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} docker://${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG
